<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dell-Home-laptop" failures="1" tests="8" name="Login(failed)" time="89.304" errors="0" timestamp="2024-11-28T09:52:09 AEST">
  <testcase classname="testCases.TC002_LogInFail" name="Verify_Login_Fail" time="2.581"/>
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="3.192"/>
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="11.545"/>
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="12.615"/>
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="2.995"/>
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="11.053"/>
  <testcase classname="testCases.TC003_LoginDataDriven" name="Verify_LoginByDataDriven" time="11.901"/>
  <testcase classname="testCases.TC001_LogInSuccess" name="Veiry_Login_Success" time="12.444">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC001_LogInSuccess.Veiry_Login_Success(TC001_LogInSuccess.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Veiry_Login_Success -->
</testsuite> <!-- Login(failed) -->
